# Generated by Django 2.1.2 on 2019-05-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_in_numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedTransit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_in_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transit',
            name='safety_in_user',
        ),
        migrations.AddField(
            model_name='joinedtransit',
            name='transit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety_in_numbers.Transit'),
        ),
    ]
