# Generated by Django 2.1.2 on 2019-05-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_in_numbers', '0002_auto_20190509_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinedtransit',
            unique_together={('safety_in_user', 'transit')},
        ),
    ]
